[package]
name = "signature-schemes-ark"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.4.2"
ark-ec = "0.4.2"
ark-std = "0.4.0"
ark-bn254 = "0.4.0"
hex = { version = "0.4", default-features = false, features = ["alloc"] }



