[package]
name = "signature-schemes-ark"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.4.2"
ark-std = "0.4.0"
ark-ec = "0.4.2"
ark-test-curves = {version = "0.4.2", features = ["bls12_381_curve"]}
hex = { version = "0.4", default-features = false, features = ["alloc"] }



